name: Pointnetwork docs github pages deployment

on:
  push:
    branches:
      - upgrade-deps-merge

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Add key to allow access to repository
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "${{ secrets.GH_PAGES_DEPLOY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          cat <<EOT >> ~/.ssh/config
          Host github.com
          HostName github.com
          IdentityFile ~/.ssh/id_rsa
          EOT
      - name: Publish to GitHub Pages
        env:
          USE_SSH: true
          GIT_USER: git
          PUBLISHING: true
        run: |
          cd website
          git config --global user.email "docs.deployment@pointnetwork.io"
          git config --global user.name "Pointnetwork deployment action"
          GIT_USER="docs.deployment@pointnetwork.io"
          CURRENT_BRANCH=main
          USE_SSH=true
          npm ci
          npm run deploy
